/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VetForm {
    }
    interface VetFormInput {
        "element": string;
        "errorMsg": string;
        "fieldId": string;
        "maxChars": number;
        "minChars": number;
        "name": string;
        "type": string;
    }
    interface VetGallery {
    }
    interface VetMap {
        "height": string;
        "provider": string;
        "src": string;
        "title": string;
        "width": string;
    }
    interface VetModal {
        "agreeBtnLabel": string;
        "close": () => Promise<void>;
        "customElement": any;
        "opened": boolean;
    }
}
declare global {
    interface HTMLVetFormElement extends Components.VetForm, HTMLStencilElement {
    }
    var HTMLVetFormElement: {
        prototype: HTMLVetFormElement;
        new (): HTMLVetFormElement;
    };
    interface HTMLVetFormInputElement extends Components.VetFormInput, HTMLStencilElement {
    }
    var HTMLVetFormInputElement: {
        prototype: HTMLVetFormInputElement;
        new (): HTMLVetFormInputElement;
    };
    interface HTMLVetGalleryElement extends Components.VetGallery, HTMLStencilElement {
    }
    var HTMLVetGalleryElement: {
        prototype: HTMLVetGalleryElement;
        new (): HTMLVetGalleryElement;
    };
    interface HTMLVetMapElement extends Components.VetMap, HTMLStencilElement {
    }
    var HTMLVetMapElement: {
        prototype: HTMLVetMapElement;
        new (): HTMLVetMapElement;
    };
    interface HTMLVetModalElement extends Components.VetModal, HTMLStencilElement {
    }
    var HTMLVetModalElement: {
        prototype: HTMLVetModalElement;
        new (): HTMLVetModalElement;
    };
    interface HTMLElementTagNameMap {
        "vet-form": HTMLVetFormElement;
        "vet-form-input": HTMLVetFormInputElement;
        "vet-gallery": HTMLVetGalleryElement;
        "vet-map": HTMLVetMapElement;
        "vet-modal": HTMLVetModalElement;
    }
}
declare namespace LocalJSX {
    interface VetForm {
    }
    interface VetFormInput {
        "element"?: string;
        "errorMsg"?: string;
        "fieldId"?: string;
        "maxChars"?: number;
        "minChars"?: number;
        "name"?: string;
        "onRefreshInputValue"?: (event: CustomEvent<any>) => void;
        "type"?: string;
    }
    interface VetGallery {
    }
    interface VetMap {
        "height"?: string;
        "provider"?: string;
        "src"?: string;
        "title"?: string;
        "width"?: string;
    }
    interface VetModal {
        "agreeBtnLabel"?: string;
        "customElement"?: any;
        "opened"?: boolean;
    }
    interface IntrinsicElements {
        "vet-form": VetForm;
        "vet-form-input": VetFormInput;
        "vet-gallery": VetGallery;
        "vet-map": VetMap;
        "vet-modal": VetModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vet-form": LocalJSX.VetForm & JSXBase.HTMLAttributes<HTMLVetFormElement>;
            "vet-form-input": LocalJSX.VetFormInput & JSXBase.HTMLAttributes<HTMLVetFormInputElement>;
            "vet-gallery": LocalJSX.VetGallery & JSXBase.HTMLAttributes<HTMLVetGalleryElement>;
            "vet-map": LocalJSX.VetMap & JSXBase.HTMLAttributes<HTMLVetMapElement>;
            "vet-modal": LocalJSX.VetModal & JSXBase.HTMLAttributes<HTMLVetModalElement>;
        }
    }
}
